# Generated by Django 6.0.1 on 2026-02-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='For_Card_Coctail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('type', models.TextField()),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('glass', models.TextField()),
                ('strength', models.CharField(max_length=8)),
                ('strengthprocent', models.IntegerField()),
                ('image', models.TextField()),
                ('temperature', models.TextField()),
                ('ctime', models.TextField()),
                ('history', models.TextField()),
                ('cooking', models.TextField()),
            ],
        ),
    ]
